apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-production
  labels:
    application: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      application: nginx
      environment: production
  template:
    metadata:
      labels:
        application: nginx
        version: 0.0.1
        release: release-1
        environment: production
        stage: production
        owner: "team_aesir"
        tier: backend
        app.kubernetes.io/name: blaster
        app.kubernetes.io/instance: blaster-xyz
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/part-of: selfservice
    spec:
      containers:
        - name: nginx-backend
          image: nginx
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
          - name: data
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: data
        configMap:
          name: nginx-files-production
