apiVersion: v1
kind: Service
metadata:
  name: web-service-production
  labels:
    application: nginx
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    application: nginx
    environment: production